version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: user_service_postgres_dev
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_user_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - user_dev_network

  redis:
    image: redis:7-alpine
    container_name: user_service_redis_dev
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_dev:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - user_dev_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: user_service_rabbitmq_dev
    ports:
      - "5673:5672"   # AMQP порт
      - "15673:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_dev:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - user_dev_network

  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_service_dev
    environment:
      DB_HOST: postgres
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: user_service
      
      REDIS_HOST: redis
      REDIS_PORT: 6379
      
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      
      SERVICE_NAME: user_service
      LOG_LEVEL: INFO
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - .:/app/user_service
    networks:
      - user_dev_network
    restart: unless-stopped

volumes:
  postgres_user_dev:
  redis_dev:
  rabbitmq_dev:

networks:
  user_dev_network:
    driver: bridge

